version: 2.1

orbs:
  node: circleci/node@5

jobs:
  build:
    executor:
      name: node/default
      tag: "14.16.1"

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install Angular App Dependencies
          command: npm ci

      - run:
          name: Build Angular App
          command: npx ng build --configuration=production

      # Store Angular dist folder as artifact
      - store_artifacts:
          path: dist
          destination: angular-build

      # Optional: persist if you want to use in next job
      - persist_to_workspace:
          root: .
          paths:
            - dist

workflows:
  version: 2
  build_only:
    jobs:
      - build
